[net_config]
app_port = 8080
# Only for dev
cookie_secret_b64enc = "RIZ0tOJnMEqcl5VE6p18DL1RZfvREES+/4nTKrciiNGSh0aNtcYO3pDTcuvlStn/c4jfR6pGL+7ZA4BHN6Q/Ow=="
# FIXME: setup on fly.io

[db_config]
host = "127.0.0.1"
port = 5432
username = "postgres"
password = "password"
db_name = "mailomat"

[email_config]
# Address currently used for sending emails.
sender_addr = "admin@majkavsek.com"
url = "https://api.postmarkapp.com"
timeout_millis = 10000
# Only for dev
auth_token = "dev_token"
