[net_config]
app_port = 8080

[db_config]
host = "127.0.0.1"
port = 5432
username = "postgres"
password = "password"
db_name = "newsletter"

[email_config]
# Address currently used for sending emails.
email_addr = "admin@majkavsek.com"
url = "https://api.postmarkapp.com/email"
