[session_config]
secure = true

[net_config]
host = [0, 0, 0, 0]
base_url = "https://mailomat.fly.dev"

# NOTE:
# Why no SSL in production?
# Fly.io Postgres lives on the same private Ipv6 network 
# and is connected to the application via Wireguard tunnels.
# I.E. the data is encrypted.
# https://fly.io/docs/networking/private-networking/
# Possible values: Disable, Require, Prefer
[db_config]
require_ssl = "Disable"
